[theme]
primaryColor = "#1863DC"
backgroundColor = "#F5F7F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#212529"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 20
